name:                pcre2
version:             1.1.2
github:              "sjshuck/hs-pcre2"
license:             Apache-2.0
license-file:        LICENSE # [LICENSE, src/c/pcre2/LICENCE] doesn't work with stack sdist
author:              "Shlomo Shuck and contributors"
maintainer:          "stevenjshuck@gmail.com"
copyright:           "2020 Shlomo Shuck"

extra-source-files:
- README.md
- ChangeLog.md
- src/c/**/*.h
- src/c/**/*.c

synopsis:            Regular expressions via the PCRE2 C library (included)
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sjshuck/hs-pcre2>

dependencies:
- base >= 4.9 && < 5
- containers
# TODO - microlens
- mtl
- streaming
- template-haskell
- text

library:
  source-dirs: src/hs
  include-dirs:
  - src/c
  - src/c/pcre2/src
  c-sources:
  # Per src/c/pcre2/NON-AUTOTOOLS-BUILD
  - src/c/pcre2/src/pcre2_auto_possess.c
  - src/c/pcre2_chartables.c
  - src/c/pcre2/src/pcre2_compile.c
  - src/c/pcre2/src/pcre2_config.c
  - src/c/pcre2/src/pcre2_context.c
  - src/c/pcre2/src/pcre2_convert.c
  - src/c/pcre2/src/pcre2_dfa_match.c
  - src/c/pcre2/src/pcre2_error.c
  - src/c/pcre2/src/pcre2_extuni.c
  - src/c/pcre2/src/pcre2_find_bracket.c
  - src/c/pcre2/src/pcre2_jit_compile.c
  - src/c/pcre2/src/pcre2_maketables.c
  - src/c/pcre2/src/pcre2_match.c
  - src/c/pcre2/src/pcre2_match_data.c
  - src/c/pcre2/src/pcre2_newline.c
  - src/c/pcre2/src/pcre2_ord2utf.c
  - src/c/pcre2/src/pcre2_pattern_info.c
  - src/c/pcre2/src/pcre2_script_run.c
  - src/c/pcre2/src/pcre2_serialize.c
  - src/c/pcre2/src/pcre2_string_utils.c
  - src/c/pcre2/src/pcre2_study.c
  - src/c/pcre2/src/pcre2_substitute.c
  - src/c/pcre2/src/pcre2_substring.c
  - src/c/pcre2/src/pcre2_tables.c
  - src/c/pcre2/src/pcre2_ucd.c
  - src/c/pcre2/src/pcre2_valid_utf.c
  - src/c/pcre2/src/pcre2_xclass.c
  ghc-options:
  - -optc=-DPCRE2_CODE_UNIT_WIDTH=16
  - -optc=-DPCRE2_STATIC=1
  - -optc=-Wno-discarded-qualifiers
  - -optc=-Wno-incompatible-pointer-types
  cc-options:
  - -DHAVE_CONFIG_H
  - -DPCRE2_CODE_UNIT_WIDTH=16
  exposed-modules:
  - Text.Regex.Pcre2
  - Text.Regex.Pcre2.Foreign

tests:
  pcre2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pcre2

    - hspec
    - microlens-platform

benchmarks:
  pcre2-benchmarks:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pcre2

    - criterion
    - microlens-platform
    - pcre-light
    - regex-pcre-builtin
